sourcing changelog bash scripts from bitbucket repository

diff --git a/.github/workflows/publish-nuget.yml b/.github/workflows/publish-nuget.yml
--- a/.github/workflows/publish-nuget.yml
+++ b/.github/workflows/publish-nuget.yml
@@ -28,8 +28,10 @@ jobs:
           TAG_NUMBERS=${TAG_VERSION#v} # Remove preceding "v" if present
           echo "TAG_NUMBERS=$TAG_NUMBERS" >> $GITHUB_ENV
 
-      - name: Check for CHANGELOG.md and replace [[TBD]] or [[tbd]]
+      - name: Check for CHANGELOG.md and update placeholders
         run: |
+          source ./lykke.snow.deployment/tools/core/changelog.sh
+
           FILES=$(find . -type f -name 'CHANGELOG.md')
           if [[ -z "$FILES" ]]; then
             echo "CHANGELOG.md not found. Failing the workflow."
@@ -41,12 +43,12 @@ jobs:
             exit 1
           fi
           FILE=$(echo "$FILES" | head -n 1)
-          if ! grep -q -E '\[\[TBD\]\]|\[\[tbd\]\]' "$FILE"; then
-            echo "[[TBD]] or [[tbd]] not found in $FILE. Failing the workflow."
+
+          replace_tbd_placeholder "$FILE" "${{ env.TAG_NUMBERS }}"
+          TBD_FOUND_FLAG=$?
+          if [[ $TBD_FOUND_FLAG -eq 0 ]]; then
+            echo "CHANGELOG.md does not contain a placeholder for the new version. Failing the workflow."
             exit 1
-          else
-            sed -i "s/\[\[TBD\]\]/${{ env.TAG_NUMBERS }}/g" "$FILE"
-            sed -i "s/\[\[tbd\]\]/${{ env.TAG_NUMBERS }}/g" "$FILE"
           fi
       
       - name: Update csproj files with new version
